spring:
  cloud:
    gateway:
      routes:
        - id: tecnos-cloud
          uri: http://tecnos-cloud:8082
          predicates:
            - Path=/cloud/**
          filters:
            - RewritePath=/cloud/(?<segment>.*), /cloud/api/v1/${segment}

        - id: tecnos-service
          uri: http://tecnos-service:8081
          predicates:
            - Path=/server/**
          filters:
            - RewritePath=/server/(?<segment>.*), /server/api/v1/${segment}

        - id: next-assets
          uri: http://clientapp:3000
          predicates:
            - Path=/ui-static/_next/static/**
          filters:
            - RewritePath=/ui-static/_next/static/(?<filename>.*), /_next/static/${filename}

        - id: media-files-ui
          uri: http://clientapp:3000
          predicates:
            - Path=/ui-static/assets/**, /ui-static/images/**, /ui-static/public/**

        - id: ui
          uri: http://clientapp:3000
          predicates:
            - Path=/ui/**
          filters:
            - RewritePath=/ui/(?<segment>.*), /${segment}

        - id: next-assets-admin
          uri: http://tecnos-management:3001
          predicates:
            - Path=/admin-static/_next/static/**
          filters:
            - RewritePath=/admin-static/_next/static/(?<filename>.*), /_next/static/${filename}

        - id: media-files
          uri: http://tecnos-management:3001
          predicates:
            - Path=/admin-static/assets/**, /admin-static/images/**, /admin-static/public/**

        - id: admin-ui
          uri: http://tecnos-management:3001
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/(?<segment>.*), /${segment}

        # Kibana Route
        - id: kibana
          uri: http://kibana:5601
          predicates:
            - Path=/kibana/**, /kibana
          filters:
            - StripPrefix=1
            - RewritePath=/(?<segment>.*), /${segment}

        # Grafana Route
        - id: grafana
          uri: http://grafana:3000
          predicates:
            - Path=/grafana/**, /grafana
          filters:
            - StripPrefix=1
            - RewritePath=/(?<segment>.*), /${segment}


      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: "https://localhost:8080 , https://89.33.44.227 , http://89.33.44.227:8080 "
            allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
            allowed-headers: "Authorization, Content-Type, Accept"
            allow-credentials: true
            max-age: 1800

  management:
    zipkin:
      tracing:
        endpoint: http://zipkin:9411/api/v2/spans

logs:
  destination: logstash:3100
