spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: tecnos-cloud
          uri: http://localhost:8082
          predicates:
            - Path=/cloud/**
          filters:
            - RewritePath=/cloud/(?<segment>.*), /cloud/api/v1/${segment}

        - id: tecnos-server
          uri: http://localhost:8081
          predicates:
            - Path=/server/**
          filters:
            - RewritePath=/server/(?<segment>.*), /server/api/v1/${segment}

        - id: ui
          uri: http://localhost:3000/
          predicates:
            - Path=/ui/**
          filters:
            - RewritePath=/ui/(?<segment>.*), /${segment}

        - id: next-assets
          uri: http://localhost:3000
          predicates:
            - Path=/ui-static/_next/static/**
          filters:
            - RewritePath=/ui-static/_next/static/(?<filename>.*), /_next/static/${filename}

        - id: media-files-ui
          uri: http://localhost:3000
          predicates:
            - Path=/ui-static/assets/**, /ui-static/images/**, /ui-static/public/**

        - id: admin-ui
          uri: http://localhost:3001
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/(?<segment>.*), /${segment}



        - id: next-assets-admin
          uri: http://localhost:3001
          predicates:
            - Path=/admin-static/_next/static/**
          filters:
            - RewritePath=/admin-static/_next/static/(?<filename>.*), /_next/static/${filename}


        - id: media-files
          uri: http://localhost:3001
          predicates:
            - Path=/admin-static/assets/**, /admin-static/images/**, /admin-static/public/**

        - id: kibana
          uri: http://localhost:5601
          predicates:
            - Path=/kibana/**
          filters:
            - RewritePath=/kibana/(?<segment>.*), /${segment}

        - id: grafana
          uri: http://localhost:3200
          predicates:
            - Path=/grafana/**
          filters:
            - RewritePath=/grafana/(?<segment>.*), /${segment}




      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: "http://localhost:8080"
            allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
            allowed-headers: "Authorization, Content-Type, Accept"
            allow-credentials: true
            max-age: 1800
  application:
    name: gateway

server:
  port: 8080

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.cloud.gateway: DEBUG

metrics:
  distribution:
    percentiles-histogram:
      http:
        server:
          request: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
    endpoint:
      prometheus:
        enabled: true
  logging:
    pattern:
      level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
    level:
      root: debug
    file:
      name: test.log

logs:
  destination: localhost:3100
